### PR TITLE
Comparison to singleton True should be expr "is"

### PR DESCRIPTION
**Pull request by FrankFeenix**
comparisons to the singleton objects, like True, False, and None should be done with identity, not equality

### CODE REVIEW

**Comment by FrankFeenix** [comment]
@gyu-don pls review some small fixs. Thansk

**Comment by gyu-don** [comment]
Thanks for your PR. Yes, it looks good to me, but `if verbose:` is better.
Could you fix it?

**Comment by FrankFeenix** [comment]
> Thanks for your PR. Yes, it looks good to me, but `if verbose:` is better.
> Could you fix it?

Done. Thank you

**Comment by gyu-don** [comment]
Thanks.

**Pull request merged**
