### PR TITLE
Circuit-Fix

### PR DESCRIPTION
**Pull request by Grandgrv**
Actual : When we apply x, z or any other single qubit gate with [:] index when no argument is provided in Circuit(), it doesn't do any gate operation. It just gives the initial qubit. 
Expected : It should do the respective single qubit gate operation.

### CODE REVIEW

**Comment by gyu-don** [comment]
Excuse me, but what is "correct output"?
To correct the bug, you must write "Expected" and "Actual", and explain why it is expected.

**Comment by Grandgrv** [comment]
Updated.

**Comment by gyu-don** [comment]
Why is it correct?

**Comment by Grandgrv** [comment]
`>>> from blueqat import Circuit
>>> c=Circuit().h[:]
>>> c.m[:]
<blueqat.circuit.Circuit object at 0x7fe786141f98>
>>> c.run()
array([1.+0.j])
`
This circuit isn't giving the right output when we are applying the Hadamard gate with [:] index. I mean to say that if we want to do Hadamard on one qubit, we need to specifically write h[0], but people have habit of writing [:] instead on [0] even for one qubit and in that case, it won't give the right output.

**Comment by gyu-don** [comment]
> but people have habit of writing [:] instead on [0] even for one qubit and in that case, it won't give the right output.

[:] means apply to all qubits, not first qubit.
For your information, following code displays "[]".

```py
import numpy as np
a = np.array([])
a[:] = 1
print(a)
```

**Comment by Grandgrv** [comment]
Yes i know it works this way. I guess we should just provide a warning in this case.

**Comment by Grandgrv** [comment]
So i guess we should just provide a warning if someone tries to use [:] when we work on a single qubit without providing an argument to the Circuit ().

**Comment by Grandgrv** [comment]
Ok i get it. It's because of the empty array. I guess we can provide a warning or error in such case.

**Comment by gyu-don** [comment]
Thank you for your advice. However, I don't feel a need to do this for now.

**Pull request closed without merging**
